# Host to use for canonical URL generation (without trailing slash)
host: https://digitalronin/technical-guidance

# Header-related options
show_govuk_logo: true
service_name: Technical Guidance
service_link: /

# Links to show on right-hand-side of header
header_links:
  # This mailto link must contain the text 'Feedback' in order to trigger the javascript
  # function in source/layouts/custom.erb which adds the current window.location to the
  # body of the resulting email message.
  'Feedback / Report a problem': 'mailto:platforms+technical-guidance@digital.justice.gov.uk?subject=Technical+Guidance+feedback'

  Documentation: /
  GitHub: https://github.com/digitalronin/technical-guidance

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: false

# Enable collapsible navigation in the sidebar
collapsible_nav: false

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true

show_contribution_banner: true
github_repo: digitalronin/technical-guidance
github_branch: main
